CREATE DATABASE testanviz;
GO
USE testanviz;
GO
CREATE TABLE Users (ID int PRIMARY KEY NOT NULL, FIO varchar(70) NOT NULL, IDANVIZ varchar(15) NOT NULL, IDTELEGRAM1 varchar(15) NULL, IDTELEGRAM2 varchar(15) NULL);
GO
CREATE TABLE Records (ID int PRIMARY KEY NOT NULL, FIO varchar(70) NOT NULL, IDANVIZ varchar(15) NOT NULL, IDTELEGRAM1 varchar(15) NULL, IDTELEGRAM2 varchar(15) NULL, CODE varchar(2) NOT NULL)
GO
